import("//build/ohos.gni")


ohos_shared_library("gateway") {
  sources = [
    "gateway_napi.cpp"
  ]

  # 极其重要：告诉编译系统我们要用到鸿蒙的 NAPI 核心库
  external_deps = [
    "napi:ace_napi"
  ]

  # 极其重要：指定生成出来的 .so 库放在系统的 module 目录下
  relative_install_dir = "module"

  subsystem_name = "gateway_subsystem"
  part_name = "gateway_component"
}